### ISSUE TITLE
Review Readme

### ISSUE THREAD

**Issue by DerikVo** [DerikVo/DSI_project_4_plant_disease#11]
Drafted a readme  (pending pull approval), will need to check for spelling, grammar and flow, and numbers. We mostly need to focus on explaining what models were using, why were using them (and not others), as well as how were evaluating these models.

We will also need to decide if we want to embed out pixel averages from our idea process, the confusion matrix from out models, or find out how to export what parts of the images the models are classifying on.

**Comment by vedapatel99** [comment]
Looks fine so far
